### ISSUE TITLE
Can't get FTP connection to work

### ISSUE THREAD

**Issue by instinctualjealousy** [dennis48309/OGXboxSoundtrackEditor#1]
Got the 1.2 binary off of SourceForge. While I've been unable to really use this, I'm happy you took it upon yourself to make a better manager. Don't know why that one guy on reddit was acting like xboxst doesn't have issues! Anyway, I'm able to connect to my Xbox with WinSCP *and* the built-in Explorer FTP, but not this. "Open from FTP" throws a "Critical Error" and "FTP Changes" throws "Failure" I notice starting this up isn't prompting the usual firewall dialog- so I figured firewall may be at fault, I just disabled Windows Firewall temporarily to test. I'm getting "Critical Error" when I try to connect to FTP, and I'm using the stock xbox/xbox credential and the Xbox's LAN IP as normal. On Win 10 x64 20H2. Running UnleashX with an Xecuter 2 BIOS (480p patched). Might be user error.

**Comment by instinctualjealousy** [comment]
I know that's not much info to go on, so I'll bring up something nonstandard that might bring up an oversight in your code, and this is me shooting blind and I could be completely wrong- my subnet is not the standard 192.168.0.*, it's 10.0.0.*, but it's still a Class C (255.255.255.0) subnet mask.

**Comment by dennis48309** [comment]
Sorry for replying extremely late, been slacking on this.  I would be happy to help troubleshoot the issue with you so I can fix the bug.

**Comment by instinctualjealousy** [comment]
I don't have the binary on my computer at the moment but I can download it again, I wish this project was a little more popular so we had more FTP test subjects haha. I assume it works okay for you?

**Comment by dennis48309** [comment]
The Windows .NET version may be a little behind in terms of the binary and source code on Github.  I have been working on a Java as well as an Android version of the app.

**Comment by dennis48309** [comment]
It would be awesome if you could help test this app to find any more bugs.  Just let me know how we can message each other.

**Comment by instinctualjealousy** [comment]
What do you have? I will be busy for a week or so as I'm heading down to Georgia to see my girlfriend but we can still figure out contact. I don't know how much help I'll be, though.

**Comment by dennis48309** [comment]
I have Messenger and Discord.  Enjoy your trip, we'll talk whenever you return.

**Comment by dennis48309** [comment]
Sorry for the extremely late supply.  I got a new job in May of last year and was so busy that I just didn't have time to work on this app.  I'm now getting back to working on it if you still want to do some troubleshooting to figure out what the issue is.

**Comment by instinctualjealousy** [comment]
I wanted to comment on this- I don't know if your FTP implementation got better, or if it's because I patched my UnleashX with a modified dashboard (FTP fix), but I'm not having issues anymore. It could've been my problem. I'm going to close this issue since I'm the only person who brought it up.
